services:
  frontend:
    image: node:22-alpine
    working_dir: /frontend
    command: sh -c "npm install && npm run dev"
    ports:
      - '3000:3000'
    volumes:
      - .:/frontend
      - node_modules:/frontend/node_modules
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
