import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Main } from '@/components';
import './global.css';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Main>{children}</Main>
        </Providers>
      </body>
    </html>
  );
}
